name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            targets: x86_64-apple-darwin
            artifact_name: numbat-ui-macos-x86_64
          - platform: macos-latest
            targets: aarch64-apple-darwin
            artifact_name: numbat-ui-macos-aarch64
          - platform: ubuntu-latest
            targets: x86_64-unknown-linux-gnu
            artifact_name: numbat-ui-linux-x86_64
          - platform: windows-latest
            targets: x86_64-pc-windows-msvc
            artifact_name: numbat-ui-windows-x86_64.exe
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.targets }}

      - name: Install dependencies (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev

      - name: Build the app
        run: cargo build --release --target ${{ matrix.targets }}

      - name: Prepare Artifact (Unix)
        if: matrix.platform != 'windows-latest'
        run: |
          mv target/${{ matrix.targets }}/release/numbat-ui ${{ matrix.artifact_name }}

      - name: Prepare Artifact (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          mv target/${{ matrix.targets }}/release/numbat-ui.exe ${{ matrix.artifact_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ matrix.artifact_name }}

      - name: Update Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v3
        if: matrix.targets == 'aarch64-apple-darwin' && !contains(github.ref, '-')
        with:
          formula-name: numbat-ui
          formula-path: Casks/numbat-ui.rb
          homebrew-tap: ${{ github.repository_owner }}/homebrew-tools
          base-branch: main
          download-url: https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/numbat-ui-macos-aarch64
          commit-message: "Update numbat-ui formula to {{version}}"
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
